apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-downloads-pv
  namespace: media
spec:
  storageClassName: nas-downloads
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.50.32.40
    path: "/volume1/Shared/Uncategorized/Downloads"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-downloads
  resources:
    requests:
      storage: 1Mi