---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: crds
  path: ./clusters/nookium/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age