---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAlLXQ0TYiWDdfZNVmujipX7vQ2vkviFKnErRPwjV4v4LLS0wYcsNIrdJxPh1NWQ+uCElBG2x4zuU6rh7cjjw1Z7zQDdnXyi/kgKK2J+KU6eH6KnwTXG80pLw9/tgYZJZ2hABfIEnsIv/iAfoVQtf0d9ZPRbXREpNDXjChD08iLrPq7LbbcAEdZJ9MU9EwUeurLI3SpZ+oLslUVKpyMFTJhztCyaYYmbw/4gEt9DO5wGPMoosRKwpQHhg69NlKgVHXz/GtzRyDqZUV9rkq2+mZqfMOp8kFc0DW9iRJ1m7YGn6x00gr5rBTa+ETmQl4PNRSn8iGy7a/QG/OOF4PYBiTYnYIweGEeJJTkzxyZHk7UmPDVonjyDp5TeZ9+4juWg7tPWm6Ad9hP4BEWMdtLwLdAf6aCgVmXnTcANtHeVIzZBY59AlSPssEcHV3cRxIExjaq53p4FeB4AZJv8BpfV5eSiMVMHgo+ErwxLkqHz4ss5CFlqmu13ccGFCcWIj8H6z0jfBMRMtSXJ6RbAaYxArJnDf/OY8z5c4EO4SCB0w1GHvko8cOLn3ioh5xwXHfP15ta4n2CuQbAFao90BVTJZWbvumx3D6x9vxTzBEeh8Z4kVODIT0VPZDDQZ1xB6oEeOhwg6AgAnwfazCYbC2rdcyphbGCcojOtZjFxEVe7OlAST6nChlf2bDExdGLab5+jDlAEXWsV96VH/+a9XDCKsQuZfYY+a7/V6/38rXF6TSrj+wtK1W4Ek4h
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque