---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.16.5
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    serviceType: LoadBalancer
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: 10.50.32.99
      annotations:
        metallb.universe.tf/allow-shared-ip: coredns
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - coredns
          topologyKey: "kubernetes.io/hostname"
    tolerations:
    - key: "arm"
      operator: "Exists"
    rbac:
      create: true
    isClusterService: false
    servers:
    - zones:
      - zone: k8s.home.mansures.net.
        scheme: dns://
        use_tcp: false
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      # - name: kubernetes
      #   parameters: cluster.local in-addr.arpa ip6.arpa
      #   configBlock: |-
      #     pods insecure
      #     fallthrough in-addr.arpa ip6.arpa
      #     ttl 30
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: file
        parameters: /etc/coredns/k8s.home.mansures.net
    zoneFiles:
     - filename: k8s.home.mansures.net
       domain: k8s.home.mansures.net
       contents: |
         k8s.home.mansures.net.		1472	IN	SOA	ns2.no-ip.com. hostmaster.no-ip.com. 2020071491 10800 1800 604800 1800
         *.k8s.home.mansures.net. IN A   10.50.32.150
