---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 42.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    grafana:
      enabled: false
      forceDeployDashboards: true
    coreDns:
      enabled: true
    kubeDns:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        hosts:
          - "prometheus.web.${SECRET_PUBLIC_DOMAIN}"
        paths:
          - /
      prometheusSpec:
        enableRemoteWriteReceiver: true
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
    alertmanager:
      enabled: false