apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
data:
    api-token: ENC[AES256_GCM,data:HSTfBhmcJQO6JP0Ax94uV1mEe51i8ONWIrjasKdKk/0xW0rpbmsC9w==,iv:GW5jAVorR3eoarrKrbbDZANATXOzbgnRAqab6mQILlQ=,tag:A6Pz7OEK6aNTm5DvQ8uF/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1skrg7ahl7k6tpavglgsanwmz6tkvnxjtuk4f07jsqynjwh0cjdns8fakda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYjlZWWNVWGJkSUhLbkZQ
            RVcvUHUwcDFTSCtBRUtLZ2JlVUpPZE5uWGhvCnZUT2VMUWxCTWsyZVY4YzlTc2VT
            Y21pQzM0dDZmVXNEcTkrbkR4aFpBUEEKLS0tIHJTVHR3U0thaWZHenBzNWI5SENO
            REJSWGIrdXZDanZoSnAzTy9IQzdoQ0EKkJs3pbnxLqEpF6AAxHlMCl2LaD9xmKHL
            LplO7l/IvWS1n12ZT3n8eA2FHvMy2JyD9smE3oXwaiLmEU6SSJaRFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-11T02:10:40Z"
    mac: ENC[AES256_GCM,data:Cp7T2vNS1jyFisWamSUQbXQYmsQUGBQsR730skfDr/9dCZABvoYCQbh/Fl0K6HqCEuilDJ85E3bmW1m7tMiCxypUXTXXh15i45WkFzb2LHUPsd9LGbwH9q0Xvge/Ibcn7mXT/5WQlwrV7XxgonNaOjs60AL4av+Fs2Tubhy5BLM=,iv:gLeUWXUSDBC3fQPFSDnpd7g7cZtqrzw7FJy9zi80QHw=,tag:pm+voaXzmfuZJbc9eOrkrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
