installation:
    enabled: true
    calicoNetwork:
      bgp: Enabled
      hostPorts: Disabled
      containerIPForwarding: Enabled
      # Note: The ipPools section cannot be modified post-install.
      ipPools:
        - blockSize: 26
          cidr: "172.20.0.0/22"
          encapsulation: VXLANCrossSubnet
          natOutgoing: Enabled
          nodeSelector: all()
      linuxDataplane: Iptables
      multiInterfaceMode: None
      nodeAddressAutodetectionV4:
        firstFound: true
    nodeMetricsPort: 9091
    typhaMetricsPort: 9093
