---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAYjnJFhEa0YOPOO4Y1ayjzat2h8g8d5I4bWva+IimUEhGDj7J2e62D+8H0P9qTdj1iAmeSgHmuNdxyOtOuMdTQY5Se8wAAXYuHPi5qDrXwlrMm93Yzgu7B2dHKCCpCiDdUvMGUsqwb6aZf3a+S7rvSUyt0gDqCt45b+eqT5azig3EsBL7pNg9HmiiGzxvm/VwKPmJdKWav0FUTUYXI1efyAYs0hShNzoKtpqEfx1jTQfe787bQwJ5zkLgODIwrgkOz9dVfRVZq1qZl7ZNWlfEwxW6zWB1uTQPOAF1IjOzWZDOJmumpAUJUGDI22D4W19Ac3hu+Q8UIIpc6Vo2xYU79ZP1eJYf6llv5q7R27H4I2SUPm1DpIV0eU7KKdL4tC0u3GI9nfe/ku7UbWkzGBaIovcEGJiS68GMx/hScI1EK1+8ckMZECW8UOq/eXdVdXviQBSoi4VUpKlD2LSW6k4SnByFa89YBSIaY7WCUfw/eE38f1NRDZwkWJnGqU17Z6GojXkSxtSeUqBYYqcp8ytIjhVKEUNqKu9btPr2FFWRUEEpY3PK+DHJbCCAAECTXYGKhL9EQGRxfJXyzpYVh0wd2u6UJDyN0IvY9GVHO/F0gCUSgMCh6kkjl54r2Zn20A0e2EVnhgiBnPmcfdm6rnt9pCZ9V5MIXnOKlopdmHApzhuFxkbP5mEaxyFxkE5lm0Yc8/katLNHOS2KxK1dltHs6YAh4luLisOtODIorYm8swosA85z+GuJ+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque