---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: calico-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://docs.projectcalico.org/charts
      chart: calico
      version: 3.21.2
      sourceRef:
        kind: HelmRepository
        name: calico-charts
        namespace: flux-system
      interval: 5m