---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 15.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1342
    podAnnotations:
      setGateway: "true"
    hostname: sonarr
    env:
      TZ: "America/Toronto"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
        - host: "sonarr.web.mansures.net"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.web.mansures.net"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      staging:
        enabled: true
        existingClaim: nas-staging-pvc
        mountPath: "/staging"
      media:
        enabled: true
        existingClaim: nas-shows-pvc
        mountPath: "/media"
    podSecurityContext:
      runAsUser: 2001
      runAsGroup: 2000
      fsGroup: 2001
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    tolerations:
    - key: "arm"
      operator: "Exists"