---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.23.1
      sourceRef:
        kind: HelmRepository
        name: project-calico-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    installation:
      enabled: true
      calicoNetwork:
        bgp: Enabled
        hostPorts: Enabled
        containerIPForwarding: Enabled
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
          - blockSize: 26
            cidr: "172.20.0.0/22"
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
        linuxDataplane: Iptables
        multiInterfaceMode: None
        nodeAddressAutodetectionV4:
          firstFound: true
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093