---
systemd:
  units:
    - name: fstrim.timer
      enabled: true
      
    - name: fstrim.service
      dropins:
        - name: override.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=/sbin/fstrim -av
storage:
  files:
    - path: /etc/motd
      overwrite: true
      mode: 0644
      contents:
        inline: |
          ___  ___                                                            _   
          |  \/  |                                                           | |  
          | .  . |  __ _  _ __   ___  _   _  _ __   ___  ___     _ __    ___ | |_ 
          | |\/| | / _` || '_ \ / __|| | | || '__| / _ \/ __|   | '_ \  / _ \| __|
          | |  | || (_| || | | |\__ \| |_| || |   |  __/\__ \ _ | | | ||  __/| |_ 
          \_|  |_/ \__,_||_| |_||___/ \__,_||_|    \___||___/(_)|_| |_| \___| \__|
          ........................................................................
          ...Deployed with Terraform - Worker Node
          ........................................................................