---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    routed_namespaces:
    - media
    settings:
      # Route internal K8s and local home traffic in to the defaullt K8S gateway
      NOT_ROUTED_TO_GATEWAY_CIDRS: "172.20.0.0/22 172.20.8.0/22"
      VPN_LOCAL_CIDRS: "10.50.0.0/16"
      # Use a different VXLAN network segment that does not conflict with the above
      VXLAN_IP_NETWORK: "172.20.16"
