---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nordvpn-secret
  namespace: vpn-gateway
spec:
  encryptedData:
    values.yaml: AgBxvJdDUvuEROCUAeeIhrvwbJE5HDMV95psrEM7Ogk6oPgSmz0I2BzXmBF9YHp0UhBeI/N5tPG3Sg2ToYSoylKDPgpLaeru3JQhgXjJlBcBUhvC7/USaSv8yJSS/O0By7cU0mV9ncghqes/FMrsFxJgpYqZLdXEeks9EQ7GrKY4megZtYFitfkwnlBerlt4tHcIE4Hz2T+qjMhF7O8fNXGKS14JwDCZcZtOV9oTi7nGJrWLyOnYiWAo4umI+7eZVw3eJT+mmFIObEIMAxlu1J6eyrw26rb/2m2gXa+fQsSEz5BZIvHf040E1W4gGIKcRCfiiboqxNSyQMT6mFlWLlza8fqq3Sfmq1gFrL8iQ82zuDszcrTTwbJs8Buz7YQIhuOQIb0pXoQOYrtKmuholYziIh+vgEXRcjoC9pg9KE+XsUMOT6LkvsLTMsm9l6TVxcms70Jen3i+bPb/l8e5B/c8QY9Ed8w2zpP3mbFpJ+EuKZSoOVbU6jYRvBPQwGAZ9xK5Lfle26IEqzHd8t6S7EDLqcFOi/zGMO5Yg+VQIpIfX3+KiTFdY9PCct/Oz7ErWJn9WNBWbiv3lmY9ySsRfVmh7/lAdLawwKDY6zkwFsRzl//Yd4ElepNYEwA3k5ktOYxWo/JxgOzxCiXkPEF3Sx1M7KEDvKFxekual+8xpTIqVgApqgw4ttuZzaxE6okMi0Z7fVnlOTvLvSC4FNUplDeFIObMTeMS+Qfx7d0ymm+Zt2hDOWLioypQFsitrEFxbmcinQIJ5QHclGC1+GPwgtdiCVVq80Fq/6xtiSKKIfOZ2k6cFJr7UKGCK43BYOe5Z7st74BxcGA4RW5w55/BB6qHI636a6Nu0uLDbR5S3NpObKfZBtwtXzd7d/a8NEI294mIJ75UV94oeoW0MUz2dBdpbJLqLIKqAfFy5UdPB62mprTE9xALycg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nordvpn-secret
      namespace: vpn-gateway
    type: Opaque
