---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nordvpn-secret
  namespace: vpn-gateway
spec:
  encryptedData:
    values.yaml: AgB/Z8ddZcabvjTXxLnzK87SZHqX6DtH/zGiufSSpSmqoJEvFDvtM4wboQ/v+H49JLvk4amUW0lE5GyFOzBlMcRcrqM6m8XwLbDbDaDEoaMGKwHkhg3OyHqNEBygFrRaoQLt/6o/Qi0b+oykz8BzbOgGkUYP+g107QJKMPZMG8XBeCwWKRgVDZCBsa5H2p9Rc9d6c3I2PGbWNLS+O4pk4qdqdjpbzjf9cttPKdXbk6s67Q3vqKaGdvcIUuWgbvczRjocBeCEVNDxPG1AJvH2vFh4wLjIpsJbZIP47lQMc2BrdraJj9n5wumaBy7NJ3Dj26iHr+HBltM4X3T468apVpZwutFM3ZAPmGHloOS2/BA3tQiMfFC+VtvtbHUcBWxSGEcGP2fmPcqjzBhwjtTwWiQhbN/3xhwzZ9oPDTGJgxWhq+iJvT7P2mz+D2ovM4TO+glrAkDM6qAJImlLMYBTKWKASCg9f9TPV3Rah6GOYf64LUgZLMEitgsSZqz2yKMJwVBQvPEM4gJz3peEJiYsHd+GTRQ5Vu2cr2iIMsdtbxQ3G3jW/yPloLDrTRIf0i7tUm7RGg7QTb1/bxONaw0QrLSthanKGoK139mIbubdA4R6XRXH20YG1ZeiKEgz/NpPM+AAT1SqsrUZ7qWoXUb/T0XW5mcoP6spU/z5pQkzJMm9QE3aYPFt1qMTRKOLRqfXPeSvwaspBvyJmoDJ/jxL6h4aEKX69oyRMSSmqAERmccOqmjkCBvNqCLLJbCf6WMQEr7VnZ1yuOMl2aQhUdJK40c9qzU5Q8q1ggTNanggStCOc2+y+hauH09IPpOy1BubcB9hkAHp6Pd40R1guWcFPcUaAG0qBoecyWbj+FQ2YDAtF8sQfPcAqcewS5vMVhbV3B/nt4Xdyjeu5vxw5fhghJOAGXJLLpEdR4WGEFC9NQuqsQmuBi+nFfqVmt4xJkyWae1++0w6Hs/VPZoVV5gMpQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nordvpn-secret
      namespace: vpn-gateway
    type: Opaque
