---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nordvpn-secret
  namespace: vpn-gateway
spec:
  encryptedData:
    values.yaml: AgAPvgS0xNyJAMlqJTyObZm/sR6wEMRz1zVT1bcZLeZ83Vu2yhe5Fb4oUDZOCK9vphgbpbaQpa6zoj44oxSy84FfuUuvLWelYp6w+fHGhyjdJHm0+0c6sB5rpm+q1mhk8+tsm4QV67w66TqnyUJ2+4japjJ/ZScVuaE/pO9aMFqtNf3UWOiCnFwnSIb2rbGAO1e4o8BxeyvlFNlUf16W3zlJALmlUnF1wPzgS+B3fx3Afe5E6kS971aZiI6vdDEA8NWVJXpHcIXkepWsZ8ZB9TLSjhZaQdTQT8l675PcMkMWRQ0pDfVDTDRSKesfSCqax4P8/ctnPHgC7bENg5NEFvTBaiTc3l62sDKFTqMmvYy1ZJWheXLZEzbYnquZW5dtHuOOxNFkLn82WVQoGrA+vBNTc088SG4Qc7baJGCKMW1REbo7CKIVTzJVTEpMMToNTdSjFCXikQAIY+JyKFNMQKEBP8oujGzjODlYmJIjloGc14K+q88rnVJO60WYGU7IXS6w3Yw+bB1rLIfb/++aC03ICtGdDbv360QDtPwhCq4qifsA3qVMJMkdPDkTfsLqPc+lmsNvFPj9bxaCcm9SHAHF+/GJJaNyUQlxUKT5cgG+0E41U2rL5ZIwInXp6k8eIAaKQYPP2hJpoANENKtOUd4la3AgK5iv4AQBXC/6jhjW4/JNwy2V1733MMwgjv+DHCERS80IS2fDwto0Gqpuu6cmcCHRJhuaPR6gFJpDxupXR29kulktIsmk5j6vzITz0yDhTiLmIjPtlRbVkBr6wZCtRJ4M0ptWpuhp2JzDeCIu/TgtJXjP4bWvJpYFDvAJh3wC5jVI5bzT9DFHRxkqyTreXlifFm4j56+KRZWc3YIPKKT7xTOndHtIl/xsbobCqnK/E+vzFX3otIw7dahT817fwwDXiRCwignSK13c3hg09/K0od4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nordvpn-secret
      namespace: vpn-gateway
    type: Opaque
