---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.44.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: grafana/grafana
      tag: latest
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - "grafana.web.${SECRET_PUBLIC_DOMAIN}"
      path: /
    persistence:
      enabled: true
      storageClassName: "fast-disks"
      size: 8Gi
    serviceMonitor:
      enabled: true
    grafana.ini:
      server:
        domain: "grafana.web.${SECRET_PUBLIC_DOMAIN}"
        root_url: "https://grafana.web.${SECRET_PUBLIC_DOMAIN}/"
        serve_from_sub_path: "true"
