---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-postgresql
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
  storageClassName: fast-disks
