---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.1
    podAnnotations:
      setGateway: "true"
    hostname: nzbget
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.50.40.21
        ports:
          http:
            port: 6789
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # nginx.ingress.kubernetes.io/auth-url: "https://auth.web.mansures.net/oauth2/auth"
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.web.mansures.net/oauth2/start
        hosts:
        - host: "nzbget.web.mansures.net"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "nzbget.web.mansures.net"
    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config-v1
      media:
        enabled: true
        existingClaim: nas-staging-pvc
        mountPath: "/media"
    podSecurityContext:
      supplementalGroups:
      - 100
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 2000Mi