---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      setGateway: "true"
    hostname: sonarr
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: "sonarr.web.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.web.${SECRET_PUBLIC_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      staging:
        enabled: true
        existingClaim: nas-staging-pvc
        mountPath: "/staging"
      media:
        enabled: true
        existingClaim: nas-shows-pvc
        mountPath: "/media"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    tolerations:
      - key: "arm"
        operator: "Exists"
    # metrics:
    #   enabled: true
