---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: core
  path: ./k8s/clusters/nookium/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system