apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:JBXVntQ+1g4n4CTv,iv:xNH6eh3l8Ps4orS8C/kZmsW/lXeCyHA9ezySlUkxaNo=,tag:xlBzCscoUjXcjsh+DnVN5Q==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:yQlzBPtGOq7XdnsZJmHG1f2l5bo7PV4i,iv:dvffd4H4W/JWm8o+SkfH1m0M2CjzHMtIXoo7Ukef4Lw=,tag:9HRcuhcZWYocwc87AO11zg==,type:str]
    NORDVPN_USER: ENC[AES256_GCM,data:EpgKrJ3cJT+EUmcef2rsNybBkzf1c6vg,iv:RC5v1yTCcemhXxrPl4PTjiPV6JjQ8Du0OzaT7FaFIKY=,tag:Wwg250FmSZEp9AgGfJgTkQ==,type:str]
    NORDVPN_PASS: ENC[AES256_GCM,data:uv7IMVyzESIyVTdB5NDfAA==,iv:A9l3KLR5CkQ67u50BRUSqXIX0UgKx6olwvJbAcJF+fE=,tag:qYGZjCHa58mYbQ/ZRzKMDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1skrg7ahl7k6tpavglgsanwmz6tkvnxjtuk4f07jsqynjwh0cjdns8fakda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUlZCL2lFdzh5dWtDTGhj
            UTczUG5ONjNsZGNGckhWc1p1VVRrS0R1VWpNClI5RGlmY0ZxTUtVZzRlMk1IRDZ6
            ZWE4aUlqOWtHTTJJK3VvUEl3VCtlbGcKLS0tIGxNRHFScE9xV25wd0xmQ0FKbkNr
            L3JNZmNYSlZpZGlIMGJZKzNmSXZUOEkKjn77VB2WwaygpS6e7d+852ogf3l0ws7z
            NxrHENHokpYgDBf7NOZ4EDhP5mWRj/py58pHeGiZ22e+elEdsGqSEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T19:06:23Z"
    mac: ENC[AES256_GCM,data:IlBZHNjlrsQOLzTeVE5dmT9TE+dUb56FiXlhk7eoUjr2m8uYSPYbk/MDYjdk6vqp1CWpDsU5u09rKMdiiRz+7JigezI/d4lSLSpuQGDIZJM0IO4UF7xBM4VigoSPfiXC+448frFAVNFvurCu//PFIiyU28dYzBZWDCBGpqMdfkQ=,iv:FTxyEp4uFoTT/gwyL7L8X/1J9ucrvPkrJ5SMcSCaL/8=,tag:EYIrOle0zNAZwJhN1YvC4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
