---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staging-area-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: slow-disks