---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets chart=sealed-secrets
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/helm-v1.16.1/helm/sealed-secrets/crds/sealedsecret-crd.yaml