---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 1
      config:
        # custom-http-errors: 404,401,403,500,503
        # hsts-max-age: "31449600"
        # global-auth-url: "http://oauth2-proxy.kube-system.svc.cluster.local/oauth2/auth"
        # global-auth-signin: "https://auth.$server_name/oauth2/start"
      use-forwarded-headers: "true"
      service:
        loadBalancerIP: 10.50.40.150
        externalTrafficPolicy: Local
      ingressClassResource:
        default: true
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: true
      #     namespace: kube-system
      #     namespaceSelector:
      #       any: true
      tolerations:
      - key: "arm"
        operator: "Exists"
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - ingress-nginx
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - ingress-nginx
              - key: app.kubernetes.io/component
                operator: In
                values:
                - controller
            topologyKey: "kubernetes.io/hostname"

      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 600Mi
    defaultBackend:
      enabled: true
      image:
        registry: k8s.gcr.io
        image: defaultbackend-amd64
        tag: "1.5"
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi