---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rack-controller
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/b-tuma/rack-controller
      tag: edge
      pullPolicy: Always
    service:
      main:
        ports:
          http:
            port: 5000
      metrics:
        enabled: true
        ports:
          metrics:
            enabled: true
            port: 9999
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: "rack-controller.web.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    securityContext:
      privileged: true
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Teensyduino_USB_Serial_1327270-if00
        hostPathType: CharDevice
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-controller
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 1500Mi
