apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:qbMmx/NThB9ZgTdN,iv:+YUbjkiKyz90pACTnwOkJqJc/QWKg4MOTfGCXl0+BlE=,tag:fmC1L7wedxpBYEUs0hyo/g==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:8Sc8PzstbHaxiN4sANls1TrrN9agGT3p,iv:JAPQJP73VOf9AsLe2AjUlGuxdrSWwrRvOzBKnKHAloI=,tag:objCT7x2Ob/UN6CJkfHgZw==,type:str]
    NORDVPN_USER: ENC[AES256_GCM,data:BDS4y2h2PxvMeqy0uE5eBLSdoRP3zinL,iv:qT90BYguAk4im31J3f9eSMflbTWnvKLislgOpXMll2E=,tag:CXdbpJjQQ3kLxn8Ia0dtMQ==,type:str]
    NORDVPN_PASS: ENC[AES256_GCM,data:x8AhVYe6whjSYBbkQW7DCQ==,iv:KAneBjsP4bjJ01ZZIfO2VlIeomPaPYO2U7EW1PpEnqE=,tag:+aK+PwovfmEiIo7+VFpO5w==,type:str]
    NORDVPN_KEY: ENC[AES256_GCM,data:AnSFZ6ezQAdWW34ZYUYAv3QmhwJf6fkVveqHHuYD5xbt+l5ifLMW/bZjcdA=,iv:Q2GNOEiJalZs/eeLbzv5uPACY0Sef1ElRqYnRVB9Iss=,tag:rLT2DP+uRB23epppJRnPew==,type:str]
    HASS_DB_PASSWORD: ENC[AES256_GCM,data:U40NcqP3cTrBYWtTjUFD9A==,iv:61D9y9dfI3AeqHoKnppCpPBc/Hzz1IhT2cKD5EUnosk=,tag:fIrq9dAviTgR0GGN/lkfog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1skrg7ahl7k6tpavglgsanwmz6tkvnxjtuk4f07jsqynjwh0cjdns8fakda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YkFzQVhRSjNTRlFUWWJm
            SU5HTmpjelpxMWFQaHdTYzZSSUl6Y1lZT3pvCnFEZCtJeFpoOTloOGUyQkFzejdQ
            TXhnNUR5OWdxZHdZKzFWQ05VR1BXRDgKLS0tIER4YThNMng0cytSZTV3R3puMlkz
            Q040c2lZNlN5aU11LzVZTjVnQXVFbEkKBeaeSPlW4+J3JIGvBcEn1qJR1DvcBl+K
            DgLTyFQKMqMGH9BS6akeI4FoHlP7DYfGldcph+TjIWK9cgBGLROJlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T20:48:22Z"
    mac: ENC[AES256_GCM,data:UljRLxLmg5mi55mZMMoOxb2tJZ+0U9aQvnAK+RWqAOoOz7xnAei3J7sqmWxlvZgHVfuNRkrlsAiyNuWhvogVtBWn9UWqXkj8eBEyOv/TOyFCnAIoqwBoZ9URndIJ1c9fh4ZBUXglZiQ2XfOxlRoaVE9fyYgvB+ETAIfLkwEqTvY=,iv:WOFf1eMRMawHv2OHB0FupoMqvyGgiZX7y1p+UKJ84CE=,tag:bnTyDULHsIwl8hacwXfY9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
