apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:eVGjRdcAJy1DoY7z,iv:zHV6KgUb9V0DAZSYllST7z09jly7Fz79DB+bCNbKzmA=,tag:18pnyqLd3X0gkViJJ5XhAQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:kkhYUFnASYxFNliSjX3foOWXYtt+nJYT,iv:xs8sXmeUQZpudB2qoOA8+UTExbIKYqMNNgVlyWQ7x4s=,tag:WiXiS8mMEhxTwi3Lklo0sQ==,type:str]
    NORDVPN_USER: ENC[AES256_GCM,data:NbE2s5fcHEtT+6GGnC46EJlk55sPyaKT,iv:lmSC5Nw1sBRnZZyLAo5X4bvWDhoeLTkOtGte/Gpx534=,tag:pwsfa7K7umImSsDd5oqpew==,type:str]
    NORDVPN_PASS: ENC[AES256_GCM,data:QYLbQXT3lkfsr6N2CFD2ZA==,iv:hyiAEhM8uBWg/qBWSjVT4a8UqtQKtGz9tyiS0owCsSE=,tag:bMqli3UXs2ISS7AD4TEDLg==,type:str]
    NORDVPN_KEY: ENC[AES256_GCM,data:naCUqamgpO28exMjwgpoQYk2HN8Ya4qOJv3smv5R5/e4CKwi9cCH+sF9g0U=,iv:NLGpAXcHg/CI5KQqDW9AnRv1Rl7GChoH/zGre/uNM2M=,tag:uq3LxgPVKpWIw27H0TjN5Q==,type:str]
    HASS_DB_PASSWORD: ENC[AES256_GCM,data:LDaHuTINJNMyVMu1RySzcw==,iv:Ct+5E2QgF0DuY9Tb1z58bfAYwAV1hGy/GJjKKelxLgs=,tag:OT2Edhl2xZZGGMtaf5JFHw==,type:str]
    OCTOPRINT_API_KEY: ENC[AES256_GCM,data:Qy5rPFhJ2Jp71wIr3E8B/64VSDgPND3URE4OpAOXdtE=,iv:XY44fG81w/pr3KeAcxqNyOLB+AHK+IjRiCocGiAcac8=,tag:ys0szZXHZVlbN4ea+Zpiiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1skrg7ahl7k6tpavglgsanwmz6tkvnxjtuk4f07jsqynjwh0cjdns8fakda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV1JxM1p1aFJjOXRjc3ZQ
            VnVhNzhXUU0xLzhQSnFTN3VjSW8xL0JaVGdBCiswSmJoOXZTb0xqdTdkcVNZQlhu
            VW9CYWJsZjBMMnVmODQ5OGVxd1hpKzgKLS0tIFB0Sm16a2w0THRocnZDN0pwQUYx
            WHlzeHFwNXBYOGVFQkt2OGpCQ0FzV2sK6YnQs2k3hwa4FiG+/s/+jv9dCdgsmik9
            gFn+V5m3EP+/sQIfJ4Dz8Sf7Ew2QlukIfFrCaG45gpn55Np+NSKt1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T18:16:24Z"
    mac: ENC[AES256_GCM,data:ppRjzh77yP5+r9TwEW9n6q/PRh/iYoWgDPG5m6fk4SJxBY3dPICJ4pOJF9ac78LHkNLnxYA3CW8jhLrbevOcwLmn+Zyhco2b0AyBexaUcKTFtD3VqevXDHU8eYsKsyqowG7v+NMTk4oOl6g1j8rB4hlUt+Yo/NReVq6DK+TxRFE=,iv:E6JhRUQaJ827Pqt6ah3CH3i3ny/buNehJcpMRjrXLXI=,tag:6PfUyhsWs8hW9A54C3L3qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
