---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: tigera-operator
      namespace: tigera-operator
  values:
    routed_namespaces:
    - media
    publicPorts:
    - hostname: qbittorrent
      IP: 10
      ports:
      - type: udp
        port: 44344
      - type: tcp
        port: 44344
    settings:
      # Route internal K8s and local home traffic in to the defaullt K8S gateway
      NOT_ROUTED_TO_GATEWAY_CIDRS: "172.20.0.0/20 10.50.0.0/16"
      VPN_LOCAL_CIDRS: "172.20.0.0/20 10.50.0.0/16"
      # Use a different VXLAN network segment that does not conflict with the above
      VXLAN_IP_NETWORK: "172.16.0"
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
    podSecurityContext:
      sysctls:
      - name: net.ipv6.conf.all.disable_ipv6
        value: "1"
      - name: net.ipv4.ip_forward
        value: "1"
    addons:
      vpn:
        enabled: true
        type: openvpn
        openvpn:
          image:
            repository: bubuntux/nordvpn
            tag: v3.12.3
            pullPolicy: IfNotPresent
        env:
          TECHNOLOGY: "NordLynx"
          USER: '${NORDVPN_USER}'
          PASS: '${NORDVPN_PASS}'
          NETWORK: "172.20.0.0/20 10.50.0.0/16"
          DNS: "172.20.8.10"
          POST_CONNECT: |
            /usr/sbin/iptables -A FORWARD -i vxlan0 -o nordlynx -j ACCEPT &&
            /usr/sbin/iptables -A FORWARD -i nordlynx -o vxlan0 -j ACCEPT &&
            /usr/sbin/iptables -A INPUT -i vxlan0 -j ACCEPT &&
            /usr/sbin/iptables -A OUTPUT -o vxlan0 -j ACCEPT
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
        networkPolicy:
          enabled: false