---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.6.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.7.0
    env:
      TZ: "${TIMEZONE}"
    routed_namespaces:
      - media
    publicPorts:
      - hostname: qbittorrent
        IP: 10
        ports:
          - type: udp
            port: 44344
          - type: tcp
            port: 44344
    settings:
      # Route internal K8s and local home traffic in to the defaullt K8S gateway
      NOT_ROUTED_TO_GATEWAY_CIDRS: "172.20.0.0/20 10.50.0.0/16"
      VPN_INTERFACE: wg0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_LOCAL_CIDRS: "172.20.0.0/20 10.50.0.0/16"
      # Use a different VXLAN network segment that does not conflict with the above
      VXLAN_IP_NETWORK: "172.16.0"
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.5.0
      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
    podSecurityContext:
      sysctls:
        - name: net.ipv6.conf.all.disable_ipv6
          value: "1"
        - name: net.ipv4.conf.all.src_valid_mark
          value: "1"
        - name: net.ipv4.ip_forward
          value: "1"
    addons:
      vpn:
        enabled: true
        type: wireguard
        wireguard:
          image:
            repository: ghcr.io/b-tuma/nordlynx
            tag: edge
            pullPolicy: Always
        env:
          PRIVATE_KEY: "${NORDVPN_KEY}"
          SKIP_INTERFACE: vxlan0
          TZ: "${TIMEZONE}"
          DNS: "172.20.8.10"
          NET_LOCAL: "172.20.0.0/20 10.50.0.0/16"
          TABLE: auto
          POST_UP: "/sbin/iptables -A FORWARD -d 172.16.0.0/24 -o vxlan0 -j ACCEPT && /sbin/iptables -A FORWARD -s 172.16.0.0/24 -i vxlan0 -j ACCEPT && /sbin/iptables -A FORWARD -i vxlan0 -o wg0 -j ACCEPT && /sbin/iptables -A FORWARD -i wg0 -o vxlan0 -j ACCEPT && /sbin/iptables -A INPUT -i vxlan0 -j ACCEPT && /sbin/iptables -A OUTPUT -o vxlan0 -j ACCEPT"
          PRE_DOWN: "/sbin/iptables -D FORWARD -d 172.16.0.0/24 -o vxlan0 -j ACCEPT && /sbin/iptables -D FORWARD -s 172.16.0.0/24 -i vxlan0 -j ACCEPT && /sbin/iptables -D FORWARD -i vxlan0 -o wg0 -j ACCEPT && /sbin/iptables -D FORWARD -i wg0 -o vxlan0 -j ACCEPT && /sbin/iptables -D INPUT -i vxlan0 -j ACCEPT && /sbin/iptables -D OUTPUT -o vxlan0 -j ACCEPT"
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(ip -br a | awk '{ print $1 }' | grep wg0) == 'wg0' ]; then exit $?; else exit 0; fi
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 1
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        networkPolicy:
          enabled: false
