---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-shows-pv
  namespace: media
spec:
  storageClassName: nfs-shows
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.50.32.40
    path: "/volume1/Shared/Videos/TV Shows"
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-shows-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shows
  resources:
    requests:
      storage: 1Mi
