---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-staging-pv
  namespace: media
spec:
  storageClassName: nfs-staging
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.50.32.40
    path: "/volume1/Shared/Uncategorized/Staging"
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-staging-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-staging
  resources:
    requests:
      storage: 1Mi
